use derive_more::Constructor;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize, Constructor)]
pub struct Hits {
    pub hits: u64,
}
impl Hits {
    // This fn new() will automatically be generated by derive_more (Constructor)
    // pub fn new() -> Self {
    //     Self { hits: 0 }
    // }
    pub fn into_inner(self) -> u64 {
        self.hits
    }
}
